[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
OPENVIKING_BASE_URL = "http://192.168.2.200:1933"

[mcp_servers.filesystem]
command = "node"
args = [
    'D:\AI IDE\CC_BOOS\claudes\.mcp\filesystem\dist\index.js',
    'D:\AI IDE\CC_BOOS',
]

[mcp_servers.sequential-thinking]
command = "node"
args = ['D:\AI IDE\CC_BOOS\node_modules\@modelcontextprotocol\server-sequential-thinking\dist\index.js']
